### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by Ziagl** [empathicqubit/vscode-cc65-vice-debug#2]
Hi,
I worked hours to get it running on a Windows 10 System and solved a lot of problems. I think my setup is now ready. The last error now is this:

![visual-studio-code-error-clang](https://user-images.githubusercontent.com/3746885/79065507-131dd800-7cb1-11ea-9e9a-8e4373f4bea3.png)

All files are created and if I run the executable manually in VICE it works. Any idea why the debugger ends with this error?

**Comment by empathicqubit** [comment]
That happens occasionally. Are you able to get past it sometimes or does it not work at all? Also, can you tell me the steps you took to get it working? I want to make changes based on the problems you encountered.

**Comment by empathicqubit** [comment]
Can you also check your output in the terminal tab? It should start one terminal for VICE and another for the user monitor.

**Comment by Ziagl** [comment]
The problem happens every time, I was not able to get a emulator window at all. I took some screenshots of installed versions:
![2020-04-19 08_34_48-About x64sc exe](https://user-images.githubusercontent.com/3746885/79681271-49aba380-8219-11ea-9b15-8f37767de746.png)

![2020-04-19 08_35_17-launch json - hello - Visual Studio Code](https://user-images.githubusercontent.com/3746885/79681276-529c7500-8219-11ea-9539-79b3289aef8f.png)

My launch.json:

![2020-04-19 08_35_41-launch json - hello - Visual Studio Code](https://user-images.githubusercontent.com/3746885/79681282-5cbe7380-8219-11ea-8be5-a76765a14927.png)

And the output:

![2020-04-19 08_37_17-launch json - hello - Visual Studio Code](https://user-images.githubusercontent.com/3746885/79681291-7364ca80-8219-11ea-95d0-6716b87c4f48.png)

![2020-04-19 08_37_35-launch json - hello - Visual Studio Code](https://user-images.githubusercontent.com/3746885/79681296-7b246f00-8219-11ea-8d34-88e60cde58e3.png)

All files are created as expected, I can run *.c64 executable manually with VICE and it works. I do not know if *.dbg is correct, but it is is much bigger than my *.c64 file, so I think that is ok.

![2020-04-19 08_43_02-hello](https://user-images.githubusercontent.com/3746885/79681340-d5253480-8219-11ea-93c6-806d484b54f6.png)

**Comment by empathicqubit** [comment]
The quotes for the arguments in the VICE command is really weird for some of the parameters. I'll take a look. Can you try switching your shell to cmd in your settings? I'm not able to use my computer right now so I'm just assuming that's a thing.

**Comment by Ziagl** [comment]
I tried with CMD as default shell with no difference.

**Comment by empathicqubit** [comment]
I made some changes in 1.1.17 that allow it to start VICE correctly, but it breaks after that, at least for me.

**Comment by empathicqubit** [comment]
I'm in the process of making some changes to VICE itself that will allow the debugger to behave more consistently in the future. For the newly discovered issues I think I will just work on getting that released first.

**Comment by empathicqubit** [comment]
Please check to see if it works for you now. I also fixed some timing issues that were causing problems in 1.1.19

**Comment by empathicqubit** [comment]
I'm going to close this issue since I think it's fixed. Please let me know if it's still broken and I'll reopen.

**Comment by Ziagl** [comment]
I can confirm that it works now. Thank you!
