### ISSUE TITLE
Question: When execution point hits a kernal routine, the IDE pops-up "Unable to open 'DISKIO.s': Unable to read file"

### ISSUE THREAD

**Issue by johnlivdahl** [empathicqubit/vscode-cc65-vice-debug#28]
I have a c project and when execution hits a kernal routine, the following happens:

Popup in IDE 
Unable to open 'DISKIO.s': Unable to read file 'c:\Users\jlivd\OneDrive\c64\cc65_Projects\DISK_IO\DISKIO\src\DISKIO.s' (Error: Unable to resolve non-existing file 'c:\Users\jlivd\OneDrive\c64\cc65_Projects\DISK_IO\DISKIO\src\DISKIO.s').

There is no such file in my project but there is a DISKIO.c that is working until a kernal routine is hit.  
I can't see how to config the debugger not to look for source files for kernal ROM routines.

I would like a way to be able to view the disassembly when the code is outside of the project's symbol range.  When the debugger is active I can't use vices monitor to see where the kernal is stuck (it appears the IEC routines don't like being stepped over.)

**Comment by empathicqubit** [comment]
I'm not sure why it would do that. Can you link your project?
