### ISSUE TITLE
Make file doesn't seem to create required PRG file with latest changes

### ISSUE THREAD

**Issue by KlausLoeffelmann** [empathicqubit/vscode-cc65-vice-debug#45]
Having updated everything so far to the latest version of VSCode and the VICE Debugger Extension, I am seeing now this error message:

![image](https://user-images.githubusercontent.com/9663150/134745791-df719d51-37cd-47a2-9d4d-098854c158e4.png)

What I cannot figure out: When I want to compile for C64, what instance in the process is actually responsible to take care of the requirement to have a PRG file (according to the error message) at the end? What am I missing?

**Comment by empathicqubit** [comment]
Can you please provide a recursive listing of your project directory after trying to run the debugger, as well as your launch configuration?

**Comment by empathicqubit** [comment]
If possible, a link to your project would also be helpful.

**Comment by KlausLoeffelmann** [comment]
Yes, those updates I already got in. Hope I didn't miss anything.
The repo where the project is in is here:

https://github.com/KlausLoeffelmann/RetroEdit

(Please note, my knowledge of linux, gcc, make is practically non-existing 🤷 - also ignore the batch files inside the repo. 
Also note, that this once worked with the previous version.)

Recursive dir output is here:
[recur_dir_output.txt](https://github.com/empathicqubit/vscode-cc65-vice-debug/files/7230354/recur_dir_output.txt)

Thanks for any help - really appreciated!!

**Comment by empathicqubit** [comment]
It seems to start if you add `${workspaceFolder}` into your prg/dbg/map file paths. I'll look into making it a little more straightforward. It should probably assume relative paths are from the `build.cwd` .

**Comment by KlausLoeffelmann** [comment]
You mean in _launch.json_?
Gonna try this.

**Comment by KlausLoeffelmann** [comment]
Yes, that does the trick!
Cool - thanks so much!

**Comment by empathicqubit** [comment]
np. Glad you're using the project. Keep me updated with how things go :)
