### ISSUE TITLE
debugger does not start correctly on macOS 10.15.6 with VICE 3.4 r39221

### ISSUE THREAD

**Issue by lukka** [empathicqubit/vscode-cc65-vice-debug#6]
I wanted to see how the debuggin experience looks like, and it did not work out of the box on macOS 10.15.6.

I built myself Vice:
```
3.4 r39221 (GTK3 3.24.17, GLib 2.64.4)

Darwin 19.6.0
Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
x86_64
```

Error that happens right after VICE is started:
```
Error: Response error: error 0x80: req_type 0x83: req_id 0xc4b5bba3
    at EventEmitter.o (/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/dist/debug-adapter.js:145:124730)
    at EventEmitter.emit (events.js:223:5)
    at f._binaryDataHandler (/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/dist/debug-adapter.js:145:120521)
    at Socket.emit (events.js:223:5)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:181:23)
```

On the VICE terminal:
```
/usr/bin/env ELECTRON_RUN_AS_NODE=1 x64sc -directory /Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system -iecdevice8 -remotemonitor -remotemonitoraddress 127.0.0.1:29302 -binarymonitor -binarymonitoraddress 127.0.0.1:29919 -autostart-warp -autostartprgmode 1 -autostart-handle-tde -initbreak 2211 -moncommands /Users/user/github/soccer64/soccer64.c64.lbl -model pal 
Initializing chip model "MOS8565" (63 cycles per line, 312 raster lines).
VSP Bug: safe channels are: 12345. Emulation of memory corruption is disabled.
VSP Bug: safe channels are: 135. Emulation of memory corruption is disabled.
VSP Bug: safe channels are: 2346. Emulation of memory corruption is disabled.
Opening monitor command playback file: /Users/user/github/soccer64/soccer64.c64.lbl
Sampler Filedrv: Initializing chip model "MOS6569R3" (63 cycles per line, 312 raster lines).
 
*** VICE Version 3.4, rev 39221 ***
 
Welcome to x64sc, the free portable C64 Emulator.
 
Current VICE team members:
Martin Pottendorfer, Marco van den Heuvel, Fabrizio Gennari, Groepaz, 
Errol Smith, Ingo Korb, Olaf Seibert, Marcus Sutton, Kajtar Zsolt, AreaScout, 
Bas Wassink, Michael C. Martin, Christopher Phillips, David Hogan, 
Empathic Qubit.
 
This is free software with ABSOLUTELY NO WARRANTY.
See the "About VICE" command for more info.
 
Loading system file `/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system/kernal'.
Loading system file `/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system/basic'.
Loading system file `/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system/chargen'.
Loading system file `/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system/mps803'.
Palette: Loading palette `/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system/mps803.vpl'.
Loading system file `/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system/nl10-cbm'.
Palette: Loading palette `/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system/nl10.vpl'.
NL10: Printer driver initialized.
Palette: Loading palette `/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system/1520.vpl'.
Loading system file `/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system/dos1540'.
Loading system file `/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system/dos1541'.
Loading system file `/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system/d1541II'.
Loading system file `/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system/dos1570'.
Loading system file `/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system/dos1571'.
Loading system file `/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system/dos1581'.
DriveROM: Error - 2000 ROM image not found. Hardware-level 2000 emulation is not available.
DriveROM: Error - 4000 ROM image not found. Hardware-level 4000 emulation is not available.
DriveROM: Error - CMDHD ROM image not found. Hardware-level CMDHD emulation is not available.
Loading system file `/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system/dos2031'.
Loading system file `/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system/dos2040'.
Loading system file `/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system/dos3040'.
Loading system file `/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system/dos4040'.
Loading system file `/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system/dos1001'.
DriveROM: Error - D9090/9060 ROM image not found. Hardware-level D9090/9060 emulation is not available.
Drive: Finished loading ROM images.
VIC-II: Initializing chip model "MOS6569R3" (63 cycles per line, 312 raster lines).
using GTK3 backend: OpenGL
Created render thread 0
Sound: Available sound devices: coreaudio dummy fs dump wav voc iff aiff soundmovie
mac_joy: loaded HID device list with IOHIDManager. found 0 devices
mac_joy: (auto) found 0 HID devices. HID A='' B=''
mac_joy: (auto) done
Keyboard: Loading keymap `/Users/user/.vscode-insiders/extensions/entan-gl.cc65-vice-2.5.3/system/gtk3_sym.vkm'.
Keyboard: Warning - gtk3_sym.vkm: !LCBM !VCBM !LCTRL !VCTRL not defined.
Main CPU: starting at ($FFFC).
Main CPU: RESET.
sound (coreaudio_init): Found audio device with no outputs: Built-in Microphone
sound (coreaudio_init): Found output audio device: Built-in Output (Default)
sound (coreaudio_init): Found output audio device: Soundflower (2ch)
sound (coreaudio_init): Found output audio device: Soundflower (64ch)
sound (coreaudio_init): Using output audio device: Built-in Output
Sound: Opened device `coreaudio', speed 44100Hz, fragment size 2.9ms, buffer size 101ms
reSID: MOS6581, filter on, sampling rate 44100Hz - resampling, pass to 19845Hz
Unit 8: RESET.
Monitor playback command: al 00FFA5 .ACPTR
**[CUT]**
Monitor playback command: al 000840 ._steps
Closed monitor command playback file: /Users/user/github/soccer64/soccer64.c64.lbl
monitor_binary_receive(): vice_network_receive() returned -1, breaking connection

```

**Comment by empathicqubit** [comment]
Hi, can you try it with the exact revision mentioned in the README? I made some changes to VICE recently in preparation for release, but haven't bothered to rebuild the extension yet because I'm waiting for 3.5 to be finalized.

**Comment by empathicqubit** [comment]
Alternatively, you could build the extension yourself from master

**Comment by empathicqubit** [comment]
Hopefully you don't run into issues with the packaging process. The test verification assumes Linux, so that may break. Let me know

**Comment by lukka** [comment]
it worked with building VICE 3.4 r39221 out of the SVN repo, and building the extension at [this commit id](https://github.com/empathicqubit/vscode-cc65-vice-debug/commit/35e18faf92a6d9cb9ef8b83dcb4aaf47c7f75a42) of this repository, and installing it onto VS Code Insiders. Great!

I tried it targeting a simple C64 program of few lines.
What i noticed is that I can use most of the functionalities if I debug a C file (i.e. main.c is present and built), but if I use an asm file (no .c files at all, only asm), I cannot. The debugging starts properly, VICE executes the asm program, but it complain about (obviously) missing csymbols.
My Makefile is the suggested one with a modification: `ASFLAGS = --cpu $(CPU) -g`

**Comment by empathicqubit** [comment]
I made a lot of modifications to get assembly debugging to work better recently, but it's not the original intended use of the debugger. You can have assembly fragments, but having an entirely assembly based program isn't supported very well. That being said, I did write a program with only one assembly file to try to improve the behavior recently. What's not working in a way you expect?

**Comment by empathicqubit** [comment]
Please send me your assembly code, if you can

**Comment by empathicqubit** [comment]
When you added the switch to your ASFLAGS, did you clean and recompile? I noticed that it wouldn't generate any spans unless you did that.

**Comment by empathicqubit** [comment]
I made a bunch of changes to improve navigation in assembly files. Things tend to slide around a lot, so thanks for pointing it out. I wrote some basic tests for assembly behavior also. Please let me know what other functionality you want improved in a new issue. Thank you!

**Comment by lukka** [comment]
@empathicqubit i'll try thenew extension out soon, thanks!
This is the very small sample of a Makefile project built with ca65, that contains a single asm file only: 
https://github.com/lukka/ca65_makefile_asm_sample

**Comment by empathicqubit** [comment]
Looking at that offhand, the hardcoded SYS may confuse it:

https://github.com/lukka/ca65_makefile_asm_sample/blob/master/src/main.asm#L8

Take a look at how the project under /src/tests/asm-project is structured if you run into any more problems. Following that a little more closely may help you avoid errors, but let me know if you find any more. I want to support as wide a variety of configurations as reasonable.

**Comment by empathicqubit** [comment]
It's better to leave any memory management stuff to your linker.cfg if possible. I've done some more complicated things like

- sfx with exomizer
- starting at $03d3 and extracting to $0801, which does still work with the debugger, because it waits for the entry address to be hit before calculating anything
- a stack sled so I could load uncompressed at $01f8
- a memory hole from $B000 on so I can load Goattracker SIDs starting from $B000, and put the screen, bitmaps, and sprites above $C000

That's here (The Makefile was handwritten. Hopefully not too confusing):

https://github.com/empathicqubit/c64-thepunchlineismachismo/blob/master/Makefile
https://github.com/empathicqubit/c64-thepunchlineismachismo/blob/master/linker.cfg
https://github.com/empathicqubit/c64-thepunchlineismachismo/blob/master/linker_sfx.cfg
